# Generated by Django 5.2.4 on 2025-08-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_body_style_car_cylinders_car_drive_car_keys_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='keys',
            field=models.BooleanField(default=False, help_text='Does the car come with keys?'),
        ),
    ]
