# Generated by Django 5.2.4 on 2025-08-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(choices=[('audi', 'AUDI'), ('bently', 'BENTLY'), ('bmw', 'BMW'), ('ford', 'FORD'), ('gmc', 'GMC'), ('honda', 'HONDA'), ('hyundai', 'HYUNDAI'), ('jaguar', 'JAGUAR'), ('jeep', 'JEEP'), ('kia', 'KIA'), ('land rover', 'LAND ROVER'), ('lexus', 'LEXUS'), ('mazda', 'MAZDA'), ('mercedes', 'MERCEDES'), ('mitsubishi', 'MITSUBISHI'), ('nissan', 'NISSAN'), ('porsche', 'PORSCHE'), ('toyota', 'TOYOTA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100),
        ),
    ]
