# Generated by Django 5.2.4 on 2025-08-08 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_car_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='cylinders',
        ),
    ]
